eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      
spring.zipkin.base-url: http://localhost:9411/
spring.sleuth.sampler.probability: 1.0
