eureka:
  client:
    register-with-eureka: true
    instance:
      prefer-ip-address: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring.zipkin.base-url: http://localhost:9411/
