eureka:
  client:
    register-with-eureka: true
    instance:
      prefer-ip-address: true
    service-url:
      defaultZone: http://localhost:8761/eureka

microservice:
  http-bin:
    endpoints:
      endpoint:
        uri: http://httpbin.org/
